### ISSUE TITLE
Create Customers Class

### ISSUE THREAD

**Issue by crex424** [crex424/EasyAppointmentManager#2]
The Customers class will contains:
- [x] CustomerID as the primary key
- [x] FirstName
- [x] LastName
- [x] DateOfBirth
- [x] Gender
- [x] PhoneNumber
- [x] Email

**Comment by TungKimProgrammer** [comment]
Hi @crex424, for the datatype of Gender, should I set it for boolean and not required? The customer might prefer not to answer so it could be null.

**Comment by crex424** [comment]
Hello @TungKimProgrammer, Good idea. Go ahead and move forward with that plan.

**Comment by TungKimProgrammer** [comment]
@crex424 So I guess the default settings are: Female is always True, Male False haha
