### ISSUE TITLE
Create a one-to-one connection between Doctor and Specialty 

### ISSUE THREAD

**Issue by crex424** [crex424/EasyAppointmentManager#52]
Create a one-to-many connection between Doctor and Specialty

**Comment by crex424** [comment]
@TungKimProgrammer Hello,
Whenever I update the database I always get the error "'FK_Clinic_Location_LocationID' is not a constraint.
Could not drop constraint. See previous errors." I am wondering if you are running into the same issue or not?

**Comment by TungKimProgrammer** [comment]
Yes, I have the same issue but somehow I found a way to fix it. Let me create a new issue to work with it and merge it to master.

**Comment by TungKimProgrammer** [comment]
what branch were you in? I could checkout and take a look

**Comment by crex424** [comment]
I am in the Campbell-Issue#52-OneToManyRelationshipBetweenDoctorSpecialty branch. I also not sure if I am connecting Doctor class to Specialty class correctly, though it looks correct.

**Comment by TungKimProgrammer** [comment]
"'FK_Clinic_Location_LocationID' is not a constraint.
This error was caused by me, I guess, when I refactored some code.
You might want to delete the EasyAppointmentManager database in SQLServer Object Explorer and Add a new Migration and then Update-Database to see if it works

**Comment by TungKimProgrammer** [comment]
I fixed the DB errors. After the pending Pull Request is merged, you could merge the master to your current branch.

**Comment by crex424** [comment]
Thank you very much.

**Comment by crex424** [comment]
@TungKimProgrammer Does a one-to-many relationship between Doctor and Specialty work for you, or do you want me to make it a one-to-one relationship to make it more simple?
