### ISSUE TITLE
DoctorsController - Create view - Refactoring

### ISSUE THREAD

**Issue by TungKimProgrammer** [crex424/EasyAppointmentManager#57]
Create view:
- [x] Display Dropdown list for Specialization/Specialty
- [x] Display Dropdown list for Clinics 
- [ ] Dropdown list for Services

Doctor class:
- [x] Remove Place Of Work??? Since we have List of Clinics in Doctor class showing a list of clinics where the doctor practices.

**Comment by TungKimProgrammer** [comment]
Hi @crex424,
Any comments on this issue?

**Comment by crex424** [comment]
The removal of Place Of Work is good with me. The other items are also good with me.

**Comment by crex424** [comment]
@TungKimProgrammer I will not be able to make a drop-down menu for Services in the Doctor create view since Services is currently not connected to Doctors. Until that happens, I believe I am finished with this issue. Let me know what you think.

**Comment by TungKimProgrammer** [comment]
@crex424,
I think we need to remove Services from Doctor class.
Services offered by a Clinic (which is run by a Doctor) 
![image](https://github.com/crex424/EasyAppointmentManager/assets/110303244/477cc555-4e86-48da-9bba-1c135c858460)
Services

**Comment by crex424** [comment]
Thats good with me.
