### ISSUE TITLE
DoctorsController - All related issues

### ISSUE THREAD

**Issue by TungKimProgrammer** [crex424/EasyAppointmentManager#67]
Edit view: Update functionality currently now working due to lack of:
- [x] #70
- [x] #71

Details/Delete view:
- [x] #72
- [x] #73

Index view:
- [x] #74
- [x] #75
- [x] Display Clinic associated with the Doctor (now we have a Doctor work at a specific Clinic, and a Clinic can have more than 1 doctor, as in this Screenshot)
![image](https://github.com/crex424/EasyAppointmentManager/assets/110303244/e0a8c2ec-bef0-41a3-9d4b-564834559cbb)

Since you have done such an amazing job on DoctorsController, do you wanna go with the flow with this issue @crex424?

Split into small issues as needed.

**Comment by crex424** [comment]
@TungKimProgrammer I will work on all things related to dropdown lists since I have already figured out how to work on this.

**Comment by TungKimProgrammer** [comment]
Actually I am learning from you on ServicesController, haha
