### ISSUE TITLE
Block access to pages of the website if the user is not logged on.

### ISSUE THREAD

**Issue by crex424** [crex424/EasyAppointmentManager#78]
When the user is not logged in they should be directed to the log in page immediately after entering the site. Once they have either logged in or created an account, then the user shall be given access to the website. 

- [ ] User is sent directly to the login page when not logged in.
- [ ] User cannot access any other pages besides the login page and the create new account page
- [ ] Once logged in the user can access all pages except. 
- [ ] The login and create new account page tabs on the nav bar should be hidden once the user has logged in. 
- [ ] When logged in, if the user tries to access the login page or create new account page via the link, the user should be redirected to 
the main page blocking access.

**Comment by TungKimProgrammer** [comment]
Can we hold it for a later stage because we still have to run and test million times, it wouldn't be convenient if we have to log in every time?

**Comment by crex424** [comment]
Thats the plan. Just adding it so I remember to add it at a later date.

**Comment by TungKimProgrammer** [comment]
I see.
